### ISSUE TITLE
[Bug]: Ollama not working: object has no attribute 'chat'

### ISSUE THREAD

**Issue by johnaiii** [danielmiessler/fabric#410] opened 2024-05-21 18:22 UTC
### What happened?

I was doing 
fabric % cat t.txt | fabric --model ollama:3-8B --pattern summarize, 
when THAT happened Error:

'NoneType' object has no attribute 'chat'

I was expecting that ollama will work with fabric on my MacBook, so I don't paid the API from OpenAI.

### Version check

- [X] Yes I was.

**Comment by epeuu** [comment] 2024-05-22 01:02
Hey there,

I encountered the same problem, and the steps below resolved it for me. 
Give them a try; they might work for you too.
Before you begin, restart the shell and try executing `fabric --setup`. 


If that doesn't work, follow these steps:

`apt-get update`
`apt-get install --reinstall build-essential`
`apt-get install python3.12-dev`
`apt install python3-full`
`pipx install numpy`
`python3 -m pipx install chroma-hnswlib --include-deps`
`pipx install .`
`fabric --setup`

**Comment by epeuu** [comment] 2024-05-22 04:50
Hey friend, @johnaiii, how are you?
 I just wanted to reach out because I saw that you're running the Ollama:3-8B model. I'm guessing that you set it up locally and connected it to Fabric. 
 If so, I would love some guidance on how you got everything set up and working together.
Also, I was wondering if you could help me with something else. You see, I'm running Windows 11 with WSL Ubuntu 24.04 LTS. I've managed to get Fabric and Ollama both installed and running on this setup, but I'm not entirely sure how they're communicating with each other.
I was wondering if it might be possible for you to give me some advice or guidance about connecting these two systems so that I can run them both locally without needing a server.

If you could help me out in any way, that would be fantastic!

**Comment by krishneshg** [comment] 2024-05-22 10:29
This can be resolved by:
export OPENAI_API_KEY="NULL"

**Comment by AriaShishegaran** [comment] 2024-05-23 10:11
@krishneshg this didn't resolve the issue, I also attempted to adding permanent params in the config file for fabric but still getting either this error above or a 401 message.

**Comment by danielmiessler** [comment] 2024-05-23 17:06
The issue here is with your ollama setup. I would reinstall it and/or make sure it's up and running.

**Closed** 2024-05-23 17:06 UTC
Labels: bug

**Comment by bennyzen** [comment] 2024-05-28 17:03
I actually got the first mentioned error while trying to use my self-hosted Ollama, which btw is working perfectly using other tools, so a configuration/installation error can basically be excluded. 

After adding the suggested env-vars, the `None` error went away, but now fabric fails differently saying:
```bash
Error: Client error '404 Not Found' for url 'https://ollama.xxx.com/v1/models'
```

There is no such endpoint under `/v1/models`. Looking at the docs, my assumption only gets confirmed.

Did I miss something crucial?

**Comment by gru3zi** [comment] 2024-05-28 21:41
Im getting the same error on my mac. Doing some testing and things dont seem consistent... 

Setup commands 

export OPENAI_BASE_URL=https://192.168.10.86:11434/
export DEFAULT_MODEL="llama3"
export OPENAI_API_KEY="NULL"

I am able to list models and run commands only when specifying a remote server and model

![2024-05-28_23-23](https://github.com/danielmiessler/fabric/assets/44057919/a763706d-fab5-4add-abce-30da4460625f)

![image](https://github.com/danielmiessler/fabric/assets/44057919/2b9ba57a-bdfb-42d3-9ea7-2558b155e6ce)

Doesnt work when I dont specify a model either.

![image](https://github.com/danielmiessler/fabric/assets/44057919/a5f6a79b-0311-40e0-b59f-d2ec3182c695)

Is there a way to get it working without having to specify the remote server and model as its obviously troublesome to have to type that out each time. 

Thanks in advance for any help.

**Comment by tim-leaf-cloud** [comment] 2024-06-01 08:25
Same for me. Trying to connect to remote ollama server 
Error: Client error '404 Not Found' for url https://myserver/v1/models

**Comment by epeuu** [comment] 2024-06-02 19:41
Hello everyone,

I have a slightly off-topic question today. I'm curious about which local language model provides the best results for working with fabric. Currently, I'm using the llama3 model, but I'm interested in knowing if there are more suitable alternatives that could potentially yield better outcomes. I've also tried aya23 8B, phi3 mini, and mistral 7B.

Additionally, if I import a custom model into Ollama, which quantization level (Q3, Q4, Q5, Q6, Q8) would deliver the best performance? I understand that higher quantization levels typically offer greater accuracy and better performance, though they also demand more resources. However, is there really that significant of a difference in practice?

Which model has worked exceptionally well for fabric and other related tasks?

Thank you for your insights!

**Comment by tim-leaf-cloud** [comment] 2024-06-03 07:44
Could it be related to this issue: 

Seems that ollama api is not fully compatible with openai api spec
https://github.com/ollama/ollama/issues/2430

**Comment by DmacMcgreg** [comment] 2024-06-18 23:35
Same issue here. Ollama is not the issue

**Comment by DmacMcgreg** [comment] 2024-06-19 14:04
Got it working.

1. vim ~/.config/fabric/.env
2. add the following:
```
OPENAI_API_KEY="NULL"
OPENAI_BASE_URL=https://127.0.0.1:11434/v1/
CLAUDE_API_KEY="NULL"
GOOGLE_API_KEY="NULL"
```

Should work now.
The last one that worked for me was making sure OPENAI_BASE_URL was https not http even if it is localhost...

Make sure to unset your local variables in case you 'exported' them in one of the earlier steps so that it uses the .env file.
eg: `unset OPENAI_BASE_URL`

**Comment by CorrM** [comment] 2024-06-20 09:08
After reading code:
https://github.com/danielmiessler/fabric/blob/1dd3bbfdf372ae63c4f4a33f7428595b8428f85a/installer/client/cli/utils.py#L43-L54

So:
- Making sure `OPENAI_API_KEY`, `OPENAI_BASE_URL`is not exported. 
  - `echo $OPENAI_API_KEY` and `echo $OPENAI_BASE_URL` should return an empty string.
  - If return any value then check `/etc/environment` file and `/etc/profile.d` folder.
- And make sure your `/.config/fabric/.env` doesn't contain any key that starts with `OPENAI_` fabric should use the default ollama URL.
- And make sure your `/.config/fabric/.env` have `DEFAULT_MODEL` key. (ex. `DEFAULT_MODEL=llama3:latest`)

**Comment by funkytaco** [comment] 2024-07-01 08:03
I'm using ollama just fine.

Maybe you're not using the models as listed via the output of `fabric --listmodels`.

For example, I put `llama3:latest`, not `ollama:...`

```sh

fabric --listmodels                                       
GPT Models:

Local Models:
CognitiveComputations/dolphin-2.9.2-qwen2-7b:Q2_K
deepseek-coder-v2:latest
llama3:latest

Claude Models:

Google Models:
```

**Comment by 0x12d3** [comment] 2024-07-05 21:22
First github post! Apologies for anything wrong and let me know if I need to fix anything.  


I reinstalled moments ago, and re-ran "--setup" but don't know where to look for the version number (neither ` fabric -v` nor `fabric --version` are recognized).

echo $OPENAI_API_KEY and $OPENAI_BASE_URL both return nothing. (i.e. are not set)

```
~$ ollama -v
ollama version is 0.1.48

~$ cat ~/.config/fabric/.env
OPENAI_API_KEY="NULL"
OPENAI_BASE_URL="http://localhost:11434/v1"
DEFAULT_MODEL="llama3:latest"

~$ echo "single word response: Marco!" | fabric -p raw_query
Error: Client error '404 Not Found' for url 'http://localhost:11434/v1/models'
```

Commenting out OPENAI_API_KEY="NULL" makes the 404 error go away.



```
~$ cat ~/.config/fabric/.env
# OPENAI_API_KEY="NULL"
OPENAI_BASE_URL="http://localhost:11434/v1"
DEFAULT_MODEL="llama3:latest"

~$ echo "single word response: Marco!" | fabric -p raw_query
Polo!
```



I'm not a programmer so please excuse my sloppy methods here:


For the working response (w/o OPEN_API_KEY defined)` netcat -l 11434` returns:
`GET /api/tags HTTP/1.1`


But when OPEN_API_KEY is present it shows fabric using:
`GET /v1/models HTTP/1.1`

To query my other machine I ended up creating an alias to add `--remoteOllamaServer 192.0.2.1`  and left the .env file blank except for the DEFAULT_MODEL assignment.  I see mentions of the /v1/model path here and on the ollama github but don't know enough to understand why it 404's. Almost certainly user error on my part.  Anyway, this has been working for me-- hope it helps somebody else.

**Comment by owen98fox** [comment] 2024-07-13 11:18
how can I make a switch for groq api and local llm ollama so that if I run out of tokens I use the local model the interface frendly way without changing the env every time?
