### ISSUE TITLE
[Bug]: Fabric Dependency Issues with gRPC and Google Cloud Libraries

### ISSUE THREAD

**Issue by joshuafuller** [danielmiessler/fabric#747] opened 2024-07-18 19:39 UTC
### What happened?

**What happened?**

I was using the `fabric` package for various commands, such as changing the default model and summarizing YouTube videos. Despite multiple attempts to reinstall `fabric` and its dependencies, I am still encountering warning messages related to `grpcio` and other related libraries. The specific warnings are:

- `WARNING: All log messages before absl::InitializeLog() is called are written to STDERR`
- `I0000 00:00:1721329796.596775   48349 check_gcp_environment.cc:61] BIOS data file does not exist or cannot be opened.`

These warnings appear consistently during different `fabric` operations, not just when changing the default model.

**Environment:**

- **Operating System:** Windows 11 with WSL2
- **Python Version:** 3.10
- **Fabric Version:** 1.4.0
- **Latest Commit:** d75ea473e64c387c69fb59ad021bd38f8b507ae3
- **Git Version:** 2.34.1
- **Dependency Versions:**
  - `grpcio==1.65.1`
  - `google-cloud-aiplatform==1.59.0`
  - `google-cloud-storage==2.17.0`

**Steps Taken to Resolve the Issue:**

1. **Full Uninstall and Reinstallation:**
   - Uninstalled `fabric` using pipx: `pipx uninstall fabric`
   - Deleted the local `fabric` repository: `rm -rf ~/github/fabric`
   - Re-cloned the `fabric` repository from GitHub: `git clone https://github.com/danielmiessler/fabric.git`
   - Reinstalled `fabric` using pipx: `pipx install fabric`
   - Re-setup `fabric` as a new installation: `fabric --setup`
   - I performed these steps twice to ensure a clean installation.

2. **Dependency Verification:**
   - Checked installed versions of key dependencies using: `pipx runpip fabric show grpcio`
   - Noted the installed versions:
     - `grpcio==1.65.1`
     - `google-cloud-aiplatform==1.59.0`
     - `google-cloud-storage==2.17.0`
   - Upgraded dependencies: `pipx runpip fabric install --upgrade grpcio google-cloud-aiplatform google-cloud-storage`

3. **Example Commands Producing Warnings:**
   - Changing the default model:
     ```sh
     fabric --changeDefaultModel gpt-4o-mini
     WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
     I0000 00:00:1721329796.587000   48349 config.cc:230] gRPC experiments enabled: call_status_override_on_cancellation, event_engine_dns, event_engine_listener, http2_stats_fix, monitoring_experiment, pick_first_new, trace_record_callops, work_serializer_clears_time_cache
     I0000 00:00:1721329796.596775   48349 check_gcp_environment.cc:61] BIOS data file does not exist or cannot be opened.
     Default model changed to gpt-4o-mini. Please restart your terminal to use it.
     ```

   - Summarizing a YouTube video (snipped for brevity):
     ```sh
     yt https://www.youtube.com/watch?v=_CwGUt0CpvU | summarize -s
     WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
     I0000 00:00:1721330542.882595   52151 config.cc:230] gRPC experiments enabled: call_status_override_on_cancellation, event_engine_dns, event_engine_listener, http2_stats_fix, monitoring_experiment, pick_first_new, trace_record_callops, work_serializer_clears_time_cache
     I0000 00:00:1721330542.888972   52151 check_gcp_environment.cc:61] BIOS data file does not exist or cannot be opened.
     [SNIPPED FOR BREVITY - Normal Output]
     ```
     The command still provided the expected output after the warning messages.

### Version check

- [X] Yes I was.

### Relevant log output

```shell
fabric --changeDefaultModel gpt-4o-mini
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1721329796.587000   48349 config.cc:230] gRPC experiments enabled: call_status_override_on_cancellation, event_engine_dns, event_engine_listener, http2_stats_fix, monitoring_experiment, pick_first_new, trace_record_callops, work_serializer_clears_time_cache
I0000 00:00:1721329796.596775   48349 check_gcp_environment.cc:61] BIOS data file does not exist or cannot be opened.
Default model changed to gpt-4o-mini. Please restart your terminal to use it.


yt https://www.youtube.com/watch?v=_CwGUt0CpvU | summarize -s
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1721330542.882595   52151 config.cc:230] gRPC experiments enabled: call_status_override_on_cancellation, event_engine_dns, event_engine_listener, http2_stats_fix, monitoring_experiment, pick_first_new, trace_record_callops, work_serializer_clears_time_cache
I0000 00:00:1721330542.888972   52151 check_gcp_environment.cc:61] BIOS data file does not exist or cannot be opened.
```

### Relevant screenshots (optional)

![WindowsTerminal_LJlCqEOP3q](https://github.com/user-attachments/assets/c57c6a81-5a7c-411d-be01-6b3d71ef55a2)

**Comment by manojkollam** [comment] 2024-07-19 00:25
I am getting the same type of behavior on a fresh install on ubuntu on WSL
--------------------------------------------------------------------------------------
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1721348702.029898  172323 config.cc:230] gRPC experiments enabled: call_status_override_on_cancellation, event_engine_dns, event_engine_listener, http2_stats_fix, monitoring_experiment, pick_first_new, trace_record_callops, work_serializer_clears_time_cache
I0000 00:00:1721348702.035481  172323 check_gcp_environment.cc:61] BIOS data file does not exist or cannot be opened.

**Comment by 07pepa** [comment] 2024-07-19 14:12
i am not using fabric and i am even seeing those mesage in cloud run in GCP in docker  python:3.12-slim (3.12.4)

my only google related dependency is` google-cloud-pubsub >=2.22.0, <3.0.0`
probably it is something deeper hopefuly they are not using intel CPUs https://www.youtube.com/watch?v=oAE4NWoyMZk
it looks CPU dependent and platform dependend on M3 (arm64)  mac i see (in arm64 docker) 

```
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1721398116.263223       1 config.cc:230] gRPC experiments enabled: call_status_override_on_cancellation, event_engine_dns, event_engine_listener, http2_stats_fix, monitoring_experiment, pick_first_new, trace_record_callops, work_serializer_clears_time_cache, work_serializer_dispatch
I0000 00:00:1721398116.263443       1 ev_epoll1_linux.cc:125] grpc epoll fd: 3
```

NOTICE:  _**BIOS data file does not exist or cannot be opened.**_   is missing

**Comment by 07pepa** [comment] 2024-07-19 14:38
imho i think it is expected there it will not work in WSL since it is realy  goes to bios file https://github.com/grpc/grpc/blob/bed04ed5761bea5adc2f04962fffd30b055c39b2/src/core/lib/security/credentials/alts/check_gcp_environment_linux.cc#L61 aka /sys/class/dmi/id/product_name

since you are running in  WSL 2 that runs in Hyper-V it wont see real hw
https://github.com/microsoft/WSL/issues/4391

SOLUTIONS:
* use full VM
* dual boot
* swich away from window and embrace *nix (mac or linux)

for those who came with similar issue from GCP cloud run just switch to second gen

**Comment by joshuafuller** [comment] 2024-07-19 16:05
@07pepa,

It's clear that your comment doesn't address the core issue we're facing and comes across as unhelpful and diversionary. It feels like trolling, which isn't appreciated here. If you don't have constructive suggestions to resolve the dependency conflicts within the fabric package, please take your comments elsewhere.

Let's keep this discussion focused and professional.

**Comment by 07pepa** [comment] 2024-07-19 18:26
Ithink it that on fryday ninght i just took too much frustration with google and its not up to snuff documentation and made it too much TLDR and little bit trolly

however after you reed folowing paragrafs you will understand why is  WSL2 Issue and you need to use something better
* i am not a a usser of fabric but i encoutered **identical issues** with my own microservise in Google cloud platforms Cloud Run v1  (its not fully linux comatible --> causes same issue )  my only dependecy is **google-cloud-pubsub>=2.22.0, <3.0.0**
* this is c++ problem not python problem the C++ repo i cited does emit those warnings
    * **google-cloud-pubsub** and fabric probably share c++  library the exact warning are  just 2 stack frames deeper i cited https://github.com/grpc/grpc/blob/bed04ed5761bea5adc2f04962fffd30b055c39b2/src/core/lib/security/credentials/alts/check_gcp_environment.cc#L61 (this is 2nd message) its line 61 that is where `check_gcp_environment.cc:61]` is comming from.
    * 1st log  message is caused by second one since it must emit to std::err before logging is set up that how well desinged logging libraries work
    * i citted previously correctly that its issue with file  **/sys/class/dmi/id/product_name** not being in WSL2 that is defined here https://github.com/grpc/grpc/blob/bed04ed5761bea5adc2f04962fffd30b055c39b2/src/core/lib/security/credentials/alts/check_gcp_environment_linux.cc#L32 
* i cited other similar issues encoutering similar problem https://github.com/microsoft/WSL/issues/4391 

hopefully now its clear **wsl2 is realy causing this**  and there is incompatibily with it.   dockerizing this may also solve it but i am not shure since it still is not full virtualization or just accesing real hw. 

i am also humbly asking to close this issue since it is clear it not issue of fabric but actual problem lies [here](https://github.com/grpc/grpc/ )   or with wsl2 and they dont vant to solve it

**Comment by joshuafuller** [comment] 2024-07-19 19:49
I found a temporary fix for the issue:

To mitigate the problem, run the following commands:

```shell
pipx runpip fabric uninstall grpcio
pipx runpip fabric install grpcio==1.64.0
```

This resolves the warning messages related to `grpcio` and other related libraries in my environment.

For more details on the grpc bug, see:
- [grpc/grpc#37222](https://github.com/grpc/grpc/issues/37222)
- [grpc/grpc#37178](https://github.com/grpc/grpc/issues/37178)

As for @07pepa's comments, they were completely useless and off-topic. They didn't help at all and only added noise to the conversation. If you can't contribute constructively, please refrain from commenting.

I hope this helps others facing the same issue.

---

**Comment by manojkollam** [comment] 2024-07-19 23:53
> I found a temporary fix for the issue:
> 
> To mitigate the problem, run the following commands:
> 
> ```shell
> pipx runpip fabric uninstall grpcio
> pipx runpip fabric install grpcio==1.64.0
> ```
> 
> This resolves the warning messages related to `grpcio` and other related libraries in my environment.
> 
> For more details on the grpc bug, see:
> 
> * [grpc/grpc#37222](https://github.com/grpc/grpc/issues/37222)
> * [grpc/grpc#37178](https://github.com/grpc/grpc/issues/37178)
> 
> As for @07pepa's comments, they were completely useless and off-topic. They didn't help at all and only added noise to the conversation. If you can't contribute constructively, please refrain from commenting.
> 
> I hope this helps others facing the same issue.

I can confirm that this fix downgrading grpcio to 1.64 is working for me as well

**Comment by andeeisaacs** [comment] 2024-07-20 01:38
Also confirming that the uninstall and reinstall of grpcio worked and resolved the warning messages.  

Thanks, @joshuafuller.

**Comment by 07pepa** [comment] 2024-07-20 05:13
JUST STOP with your pasive agresive indirect attacks on me being useless and unprofesional off topic ETC

And this could have been solved personaly witch i already attempted to do. over @joshuafuller email in github... this is **absolutly unvaranted** and could  have been solved quietly over email and not publicly

reinstalling did not solve the core of issue its still WSL... you just sidesteped it and it may show itself again when same C++ dependency will be picked up. (yes  google libraries to put it plainly are dependency hellscape)

**please prove my solution wrong!**  Then i will agree completly with your view and make Fool of myself.

i genuinely tried to help.

 **if  @joshuafuller  and @ericstamper can't prove my solutions/explanations wrong** then please concact me and we will talk privately as adults.

**Comment by pepe-rtmlab** [comment] 2024-07-20 06:06
@danielmiessler please mediate this

**Comment by 07pepa** [comment] 2024-07-20 06:07
@danielmiessler please mediate this

**Comment by joshuafuller** [comment] 2024-07-20 18:14
@07pepa,

I felt compelled to share your recent emails with the community here to ensure transparency and address your concerns publicly.

---

#### Email 1:

**Subject: "Never attribute to malice that which is adequately explained by stupidity."**

From: Josef Havránek <jhpepa@gmail.com>

```
Hello i am 07pepa from https://github.com/danielmiessler/fabric/issues/747

i do not want to drag you throu the mud there publicly but next time please use
halons razor https://en.wikipedia.org/wiki/Hanlon%27s_razor
sometime people do stupid things after all we are all humans. and your coments are partily unvaranted and go too much into passive agresive (by your github profile i can guess its caused by stress)

also beffore your comment 2 people <3 my response.... it was clear as it was helpfull profesional and foccused and you indirectly accused me that i am not.

I sugest for you to take terapy and counseling since it is painfully obvious to me as someone who also came through some shit as well you need it.

Only think i require from you is to take honest resto-instrospective and question yoursel if you had to write such snarky passive coments.

Josef
```

---

#### Email 2:

**Subject: heads up by 07pepa**

From: Josef Havránek <jhpepa@gmail.com>

```
If i am proved right i will be pressing compensation for damages that you caused me by defamation.

i am open to go out of court way but that depends on your cooperation.

i already taken screenshots and i am just warning you not to delete anything retroactively it is a evidence and i already took screenshots
```

---

I don't know what to say other than "Thank you". This has made my day.

To commemorate your unique contributions, I’ve crafted a special certificate for you. You can find it [here](https://imgur.com/a/master-of-unsolicited-advice-legal-threats-JUBA2PH).

![Master of Unsolicited Advice and Legal Threats](https://i.imgur.com/j8yndFT.png)

This will always be in my heart. Thank you, Peepee.
Feel free to print it out and frame it. You’ve earned it.

Best regards,
❤️Josh❤️

**Comment by 07pepa** [comment] 2024-07-20 18:30
Lets se how this gets closed then we will see and i am open to go other way.... 

.... But this is clearly tihs is DOXING..
 you shod redact email you DO NOT HAVE MY PREMISSION TO SHARE it.... REDACT my email adres now...

**Comment by 07pepa** [comment] 2024-07-20 18:37
anyway iam still waiting for how my explanation and solution are wrong

**Comment by 07pepa** [comment] 2024-07-20 18:38
and yes i already admited trolling erlier... but this is over the line

**Comment by 07pepa** [comment] 2024-07-20 18:38
why are you doing this @joshuafuller

**Comment by 07pepa** [comment] 2024-07-20 18:45
@joshuafuller  intent of those email was to snap to your senses..... you have been reported

**Comment by 07pepa** [comment] 2024-07-20 18:48
i wanted to continue to have this offtopic conversation over email but you doubled down and tripled down..... and doxed me.... I AM HAVING MENTAL BREAKDOWN NOW..... i addmit my errors and issues

**Comment by 07pepa** [comment] 2024-07-20 18:50
@joshuafuller were my solution i tried...?

**Comment by 07pepa** [comment] 2024-07-20 18:52
@joshuafuller  you starded the drama

**Comment by 07pepa** [comment] 2024-07-20 18:53
am i insane ? shoud i go to psychyatry??? i no longer belevie there is any GOOD in this word....

**Comment by 07pepa** [comment] 2024-07-20 18:56
can or can't  i read the code i no longer know ,..... i do no lonnger care... i will only contribute to OSS in my day job.... @joshuafuller  you win.... i am out

**Comment by fearby** [comment] 2024-07-21 08:54
MacOS same problem and fix doesn't work

**Comment by joshuafuller** [comment] 2024-07-22 18:21
> can or can't i read the code i no longer know ,..... i do no lonnger care... i will only contribute to OSS in my day job.... @joshuafuller you win.... i am out

@07pepa 

See, you said you where "out" implying that you were done. But then you reached out to my company demanding I be fired for my transgressions! Thanks for the laugh. We all got a kick out of irate and unhinged demands in the morning meeting.

But seriously. I know a lovers quarrel when I see one.  If you're looking for love and attention, just ask me out already. You don't need to be calling my people at work asking if I like you. We can skip the drama and go straight to happily-ever-after. You big handsome man. 😉❤️

**Comment by ph3ll3r** [comment] 2024-07-24 21:34
I only want to use Google's models/gemini-1.5-pro and ollama models.  I want exclude for the time being OpenAI (fabric default) and Claude.ai.  

After a reboot,  I get this error "Error: Client error '401 Unauthorized' for url 'https://api.openai.com/v1/models'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401"

I followed the suggested format a similar way described by Joshua Fuller 

Full Uninstall and Reinstallation:

1. Uninstalled fabric using pipx: pipx uninstall fabric
2. Deleted the local fabric repository: rm -rf ~/github/fabric
3. Re-cloned the fabric repository from GitHub: git clone https://github.com/danielmiessler/fabric.git
4. Reinstalled fabric using pipx: pipx install fabric
5. Re-setup fabric as a new installation: fabric --setup
-    Bypassed the openai key and claude.ai key
-    Inserted  Google  generative ai api key and youtube api key

7. I performed these steps twice to ensure a clean installation.

I tested that fabric was installed properly:

1. fabric --listmodels and found models/gemini-1.5-pro
2. fabric --changeDefaultModel models/gemini-1.5-pro
3. At this point the gRPC error, was still occurring but I was getting answers from fabric

Once, I reboot OpenAI took precedence and returned the error "Error: Client error '401 Unauthorized' for url 'https://api.openai.com/v1/models'".  This reminds me of the "Harry Belafonte & Odetta - A Hole in the Bucket: "https://www.youtube.com/watch?v=xVAvMIhvqfk"

There needs to be a way to persist  fabric --changeDefaultModel.  

Also, add as many keys as you like but have a way to reset a combination of keys which are dynamically persisted but can be changed and restart the shell and happy fabric-ing to handle as an example (Fabric: This OPENSOURCE AI Framework can AUTOMATE YOUR LIFE & ANY TASK (Setup with Ollama & Groq) : "https://www.youtube.com/watch?v=Iup3-Jvkrhg" ) as a permutation of the ability to reset a combination of keys

**Comment by joshuafuller** [comment] 2024-07-25 13:51
@ph3ll3r, it looks like your issue differs from the one I originally reported. You might want to start a new thread to address your specific problem.

The error I encountered affected all Fabric operations and involved warnings related to grpcio and other libraries, such as:
```
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1721329796.596775   48349 check_gcp_environment.cc:61] BIOS data file does not exist or cannot be opened.
```

These warnings occurred during various commands, including changing the default model and summarizing YouTube videos.

Your error seems to be a 401 Unauthorized error related to OpenAI's API after a reboot, which suggests a different underlying issue.

Please refer to the photo I uploaded to see the differences in our issues.

**Comment by th3f001** [comment] 2024-07-27 19:57
> I found a temporary fix for the issue:
> 
> To mitigate the problem, run the following commands:
> 
> ```shell
> pipx runpip fabric uninstall grpcio
> pipx runpip fabric install grpcio==1.64.0
> ```
> 
> This resolves the warning messages related to `grpcio` and other related libraries in my environment.
> 
> For more details on the grpc bug, see:
> 
> * [grpc/grpc#37222](https://github.com/grpc/grpc/issues/37222)
> * [grpc/grpc#37178](https://github.com/grpc/grpc/issues/37178)
> 
> As for @07pepa's comments, they were completely useless and off-topic. They didn't help at all and only added noise to the conversation. If you can't contribute constructively, please refrain from commenting.
> 
> I hope this helps others facing the same issue.

On MacOS Sonoma 14.5.1 the reported fix works. Thanks!

**Comment by ph3ll3r** [comment] 2024-07-28 16:09
# I used this and it did not work.
## Dependency Verification:
### Checked installed versions of key dependencies using: pipx runpip fabric show grpcio
#### Noted the installed versions:

- grpcio==1.65.1 fails but 1.64 works 
- google-cloud-aiplatform==1.59.0
- google-cloud-storage==2.17.0
- Upgraded dependencies: pipx runpip fabric install --upgrade grpcio google-cloud-aiplatform google-cloud-storage

# [th3f001](https://github.com/th3f001) commented [20 hours ago](https://github.com/danielmiessler/fabric/issues/747#issuecomment-2254239998)
## To mitigate the problem, run the following commands:
### worked perfectly
-  pipx runpip fabric uninstall grpcio
-  pipx runpip fabric install grpcio==1.64.0

**Comment by fcalazans** [comment] 2024-08-03 20:57
Having the same problem with the initial message of the thread:

```
❯ fabric --listmodels
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1722717785.434341  880089 check_gcp_environment_no_op.cc:29] ALTS: Platforms other than Linux and Windows are not supported
I0000 00:00:1722717786.424544  880089 check_gcp_environment_no_op.cc:29] ALTS: Platforms other than Linux and Windows are not supported
```

**Device:**
MacBook Pro
14-inch, 2023
Chip: Apple M2 Pro
Memory: 16 GB
macOS: 14.6 (23G80)

## worked perfectly
- `pipx runpip fabric uninstall grpcio`
- `pipx runpip fabric install grpcio==1.64.`

**Closed** 2024-08-16 19:30 UTC
Labels: bug
